from .exercises import Exercise

exerciseArr = [Exercise(name= 'Badminton', cpm=0.044, exerciseType='default'),
Exercise(name= 'Basketball', cpm=0.063, exerciseType='default'),
Exercise(name= 'Bicycling (5.5 mph)', cpm=0.029, exerciseType='default'),
Exercise(name= 'Bicycling (9.5 mph)', cpm=0.045, exerciseType='default'),
Exercise(name= 'Climbing hills (no load)', cpm=0.055, exerciseType='default'),
Exercise(name= 'Climbing hills (9 lb. load)', cpm=0.058, exerciseType='default'),
Exercise(name= 'Climbing hills (22 lb. load)', cpm=0.064, exerciseType='default'),
Exercise(name= 'Cooking', cpm=0.022, exerciseType='default'),
Exercise(name= 'Dancing, Ballroom', cpm=0.023, exerciseType='default'),
Exercise(name= 'Dance, Aerobic, medium', cpm=0.046, exerciseType='default'),
Exercise(name= 'Dance, Aerobic, intense', cpm=0.061, exerciseType='default'),
Exercise(name= 'Golf', cpm=0.038, exerciseType='default'),
Exercise(name= 'Grocery shopping', cpm=0.028, exerciseType='default'),
Exercise(name= 'Jumping rope (70 jumps per minute)', cpm=0.074, exerciseType='default'),
Exercise(name= 'Jumping rope (125 jumps per minute)', cpm=0.08, exerciseType='default'),
Exercise(name= 'Jumping rope (145 jumps per minute)', cpm=0.089, exerciseType='default'),
Exercise(name= 'Mowing the lawn', cpm=0.051, exerciseType='default'),
Exercise(name= 'Raquetball', cpm=0.081, exerciseType='default'),
Exercise(name= 'Raking leaves', cpm=0.025, exerciseType='default'),
Exercise(name= 'running (6-minute mile)', cpm=0.115, exerciseType='default'),
Exercise(name= 'running (8-minute mile)', cpm=0.095, exerciseType='default'),
Exercise(name= 'running (9-minute mile)', cpm=0.087, exerciseType='default'),
Exercise(name= 'Sitting still', cpm=0.009, exerciseType='default'),
Exercise(name= 'Skiing, cross-country, walking', cpm=0.065, exerciseType='default'),
Exercise(name= 'Skiing, cross-country, uphill', cpm=0.125, exerciseType='default'),
Exercise(name= 'Snowshoeing, soft snow', cpm=0.075, exerciseType='default'),
Exercise(name= 'Squats', cpm=0.096, exerciseType='default'),
Exercise(name= 'Swimming, crawl, slow', cpm=0.058, exerciseType='default'),
Exercise(name= 'Swimming, crawl, fast', cpm=0.071, exerciseType='default'),
Exercise(name= 'Swimming, breast stroke, fast', cpm=0.074, exerciseType='default'),
Exercise(name= 'Table tennis', cpm=0.031, exerciseType='default'),
Exercise(name= 'Walking, normal pace, asphalt road', cpm=0.036, exerciseType='default'),
Exercise(name= 'Walking, normal pace, fields and hills', cpm=0.037, exerciseType='default'),
Exercise(name= 'weeding', cpm=0.033, exerciseType='default'),
Exercise(name= 'Weight training, free-weights', cpm=0.039, exerciseType='default'),
Exercise(name= 'weight training, circuit training', cpm=0.042, exerciseType='default')
]