from .exercises import Exercise

exerciseArr = [Exercise(name= 'Badminton', cpm=4.4, exerciseType='default'),
Exercise(name= 'Basketball', cpm=6.3, exerciseType='default'),
Exercise(name= 'Bicycling (5.5 mph)', cpm=2.9, exerciseType='default'),
Exercise(name= 'Bicycling (9.5 mph)', cpm=4.5, exerciseType='default'),
Exercise(name= 'Climbing hills (no load)', cpm=5.5, exerciseType='default'),
Exercise(name= 'Climbing hills (9 lb. load)', cpm=5.8, exerciseType='default'),
Exercise(name= 'Climbing hills (22 lb. load)', cpm=6.4, exerciseType='default'),
Exercise(name= 'Cooking', cpm=2.2, exerciseType='default'),
Exercise(name= 'Dancing, Ballroom', cpm=2.3, exerciseType='default'),
Exercise(name= 'Dance, Aerobic, medium', cpm=4.6, exerciseType='default'),
Exercise(name= 'Dance, Aerobic, intense', cpm=6.1, exerciseType='default'),
Exercise(name= 'Golf', cpm=3.8, exerciseType='default'),
Exercise(name= 'Grocery shopping', cpm=2.8, exerciseType='default'),
Exercise(name= 'Jumping rope (70 jumps per minute)', cpm=7.4, exerciseType='default'),
Exercise(name= 'Jumping rope (125 jumps per minute)', cpm=8, exerciseType='default'),
Exercise(name= 'Jumping rope (145 jumps per minute)', cpm=8.9, exerciseType='default'),
Exercise(name= 'Mowing the lawn', cpm=5.1, exerciseType='default'),
Exercise(name= 'Raquetball', cpm=8.1, exerciseType='default'),
Exercise(name= 'Raking leaves', cpm=2.5, exerciseType='default'),
Exercise(name= 'running (6-minute mile)', cpm=11.5, exerciseType='default'),
Exercise(name= 'running (8-minute mile)', cpm=9.5, exerciseType='default'),
Exercise(name= 'running (9-minute mile)', cpm=8.7, exerciseType='default'),
Exercise(name= 'Sitting still', cpm=0.9, exerciseType='default'),
Exercise(name= 'Skiing, cross-country, walking', cpm=6.5, exerciseType='default'),
Exercise(name= 'Skiing, cross-country, uphill', cpm=12.5, exerciseType='default'),
Exercise(name= 'Snowshoeing, soft snow', cpm=7.5, exerciseType='default'),
Exercise(name= 'Squats', cpm=9.6, exerciseType='default'),
Exercise(name= 'Swimming, crawl, slow', cpm=5.8, exerciseType='default'),
Exercise(name= 'Swimming, crawl, fast', cpm=7.1, exerciseType='default'),
Exercise(name= 'Swimming, breast stroke, fast', cpm=7.4, exerciseType='default'),
Exercise(name= 'Table tennis', cpm=3.1, exerciseType='default'),
Exercise(name= 'Walking, normal pace, asphalt road', cpm=3.6, exerciseType='default'),
Exercise(name= 'Walking, normal pace, fields and hills', cpm=3.7, exerciseType='default'),
Exercise(name= 'weeding', cpm=3.3, exerciseType='default'),
Exercise(name= 'Weight training, free-weights', cpm=3.9, exerciseType='default'),
Exercise(name= 'weight training, circuit training', cpm=4.2, exerciseType='default')
]