from .foods import Food

foodArray = [Food(name= 'Alligator',calories=355,serving='1 serving (153 g)', foodType='default'),
Food(name= 'Beef',calories=407,serving='1 steak (164 g)', foodType='default'),
Food(name= 'Beef Brisket',calories=4308,serving='1 piece (1780 g)', foodType='default'),
Food(name= 'Beef Jerky',calories=82,serving='1 piece (20 g)', foodType='default'),
Food(name= 'Beef Ribs',calories=536,serving='1 piece (225 g)', foodType='default'),
Food(name= 'Beef Tenderloin',calories=305,serving='1 steak (140 g)', foodType='default'),
Food(name= 'Chicken',calories=731,serving='1/2 chicken (334 g)', foodType='default'),
Food(name= 'Chicken Breast',calories=344,serving='1 breast (200 g)', foodType='default'),
Food(name= 'Chicken Drumstick',calories=131,serving='1 drumstick (71 g)', foodType='default'),
Food(name= 'Chicken Fat',calories=1841,serving='1 cup (205 g)', foodType='default'),
Food(name= 'Chicken Giblets',calories=229,serving='1 cup (145 g)', foodType='default'),
Food(name= 'Chicken Gizzards',calories=212,serving='1 cup (145 g)', foodType='default'),
Food(name= 'Chicken Leg',calories=346,serving='1 leg (199 g)', foodType='default'),
Food(name= 'Chicken Liver',calories=73,serving='1 liver (44 g)', foodType='default'),
Food(name= 'Chicken Meat',calories=344,serving='1 breast (200 g)', foodType='default'),
Food(name= 'Chicken Thigh',calories=254,serving='1 thigh (111 g)', foodType='default'),
Food(name= 'Chicken Wing',calories=77,serving='1 wing (29 g)', foodType='default'),
Food(name= 'Chuck Steak',calories=859,serving='1 steak (310 g)', foodType='default'),
Food(name= 'Cubed Steak',calories=328,serving='1 serving (165 g)', foodType='default'),
Food(name= 'Duck',calories=2137,serving='1/2 duck (634 g)', foodType='default'),
Food(name= 'Filet Mignon',calories=278,serving='1 fillet (104 g)', foodType='default'),
Food(name= 'Flank Steak',calories=365,serving='1 steak (188 g)', foodType='default'),
Food(name= 'Flat Iron Steak',calories=345,serving='1 steak (252 g)', foodType='default'),
Food(name= 'Ground Beef',calories=172,serving='1 patty (70 g)', foodType='default'),
Food(name= 'Ground Round',calories=278,serving='1 piece (113 g)', foodType='default'),
Food(name= 'Ham',calories=236,serving='1 slice (145 g)', foodType='default'),
Food(name= 'New York Strip Steak',calories=426,serving='1 steak (214 g)', foodType='default'),
Food(name= 'Ostrich',calories=123,serving='1 serving (85 g)', foodType='default'),
Food(name= 'Pork',calories=363,serving='1 chop (185 g)', foodType='default'),
Food(name= 'Pork Baby Back Ribs',calories=148,serving='1 rib (70 g)', foodType='default'),
Food(name= 'Pork Chops',calories=257,serving='1 chop (131 g)', foodType='default'),
Food(name= 'Pork Country-Style Ribs',calories=148,serving='1 rib (60 g)', foodType='default'),
Food(name= 'Pork Loin',calories=169,serving='1 chop (83 g)', foodType='default'),
Food(name= 'Pork Roast',calories=2108,serving='1 roast (830 g)', foodType='default'),
Food(name= 'Pork Steaks',calories=517,serving='1 steak (264 g)', foodType='default'),
Food(name= 'Roast Beef',calories=721,serving='1 roast (515 g)', foodType='default'),
Food(name= 'Round Steak',calories=430,serving='1 steak (236 g)', foodType='default'),
Food(name= 'Schnitzel',calories=203,serving='1 schnitzel (130 g)', foodType='default'),
Food(name= 'Spare Ribs',calories=3332,serving='1 rack (1400 g)', foodType='default'),
Food(name= 'Standing Rib Roast',calories=376,serving='1 serving (113 g)', foodType='default'),
Food(name= 'T-Bone Steak',calories=580,serving='1 steak (287 g)', foodType='default'),
Food(name= 'Turkey',calories=7205,serving='1 turkey (3812 g)', foodType='default'),
Food(name= 'Turkey Breast',calories=1166,serving='1/2 breast (864 g)', foodType='default'),
Food(name= 'Turkey Legs',calories=1136,serving='1 leg (546 g)', foodType='default'),
Food(name= 'Turkey Steak',calories=321,serving='1 steak (170 g)', foodType='default'),
Food(name= 'Turkey Wings',calories=53,serving='1 wing (24 g)', foodType='default'),
Food(name= 'Artichoke',calories=60,serving='1 artichoke (128 g)', foodType='default'),
Food(name= 'Arugula',calories=1,serving='1 leaf (2 g)', foodType='default'),
Food(name= 'Asparagus',calories=2,serving='1 spear (12 g)', foodType='default'),
Food(name= 'Aubergine',calories=115,serving='1 aubergine (458 g)', foodType='default'),
Food(name= 'Beetroot',calories=35,serving='1 beet (82 g)', foodType='default'),
Food(name= 'Bell Pepper',calories=15,serving='1 pepper (73 g)', foodType='default'),
Food(name= 'Black Olives',calories=2,serving='1 olive (2.7 g)', foodType='default'),
Food(name= 'Broccoli',calories=207,serving='1 bunch (608 g)', foodType='default'),
Food(name= 'Brussels Sprouts',calories=8,serving='1 sprout (19 g)', foodType='default'),
Food(name= 'Cabbage',calories=227,serving='1 head (908 g)', foodType='default'),
Food(name= 'Capsicum',calories=12,serving='1 pepper (45 g)', foodType='default'),
Food(name= 'Carrot',calories=25,serving='1 carrot (61 g)', foodType='default'),
Food(name= 'Cauliflower',calories=3,serving='1 floweret (13 g)', foodType='default'),
Food(name= 'Celery',calories=6,serving='1 stalk (40 g)', foodType='default'),
Food(name= 'Chard',calories=9,serving='1 leaf (48 g)', foodType='default'),
Food(name= 'Cherry Tomato',calories=20,serving='1 cherry tomato (20 g)', foodType='default'),
Food(name= 'Chicory',calories=38,serving='1 head (53 g)', foodType='default'),
Food(name= 'Chinese Cabbage',calories=134,serving='1 head (840 g)', foodType='default'),
Food(name= 'Chives',calories=1,serving='1 tbsp, chopped (3 g)', foodType='default'),
Food(name= 'Collard Greens',calories=12,serving='1 cup, raw (36 g)', foodType='default'),
Food(name= 'Corn',calories=562,serving='1 cup (154 g)', foodType='default'),
Food(name= 'Courgette',calories=33,serving='1 courgette (196 g)', foodType='default'),
Food(name= 'Creamed Spinach',calories=148,serving='1 cup (200 g)', foodType='default'),
Food(name= 'Cucumber',calories=66,serving='1 cucumber (410 g)', foodType='default'),
Food(name= 'Eggplant',calories=115,serving='1 eggplant (458 g)', foodType='default'),
Food(name= 'Endive',calories=87,serving='1 head (513 g)', foodType='default'),
Food(name= 'Fennel',calories=73,serving='1 bulb (234 g)', foodType='default'),
Food(name= 'Garlic',calories=4,serving='1 clove (3 g)', foodType='default'),
Food(name= 'Gherkin',calories=9,serving='1 gherkin (65 g)', foodType='default'),
Food(name= 'Gourd',calories=108,serving='1 gourd (771 g)', foodType='default'),
Food(name= 'Green Beans',calories=34,serving='1 cup (110 g)', foodType='default'),
Food(name= 'Green Olives',calories=2,serving='1 olive (2.7 g)', foodType='default'),
Food(name= 'Green Onion',calories=5,serving='1 green onion (15 g)', foodType='default'),
Food(name= 'Horseradish',calories=7,serving='1 tbsp (15 g)', foodType='default'),
Food(name= 'Kale',calories=33,serving='1 cup, chopped (67 g)', foodType='default'),
Food(name= 'Kohlrabi',calories=108,serving='1 kohlrabi (400 g)', foodType='default'),
Food(name= 'Kumara',calories=112,serving='1 kumara (130 g)', foodType='default'),
Food(name= 'Leek',calories=54,serving='1 leek (89 g)', foodType='default'),
Food(name= 'Lettuce',calories=90,serving='1 head (600 g)', foodType='default'),
Food(name= 'Mushrooms',calories=1,serving='1 mushroom (5.4 g)', foodType='default'),
Food(name= 'Mustard Greens',calories=15,serving='1 cup, chopped (56 g)', foodType='default'),
Food(name= 'Nori',calories=1,serving='1 sheet (2.6 g)', foodType='default'),
Food(name= 'Okra',calories=4,serving='1 pod (12 g)', foodType='default'),
Food(name= 'Olives',calories=2,serving='1 olive (2.7 g)', foodType='default'),
Food(name= 'Onion',calories=34,serving='1 onion (85 g)', foodType='default'),
Food(name= 'Parsnips',calories=128,serving='1 parsnip (170 g)', foodType='default'),
Food(name= 'Peas',calories=79,serving='1 cup (98 g)', foodType='default'),
Food(name= 'Pepper',calories=20,serving='1 pepper (75 g)', foodType='default'),
Food(name= 'Potato',calories=164,serving='1 potato (213 g)', foodType='default'),
Food(name= 'Pumpkin',calories=51,serving='1 pumpkin (196 g)', foodType='default'),
Food(name= 'Radishes',calories=1,serving='1 radish (4.5 g)', foodType='default'),
Food(name= 'Red Cabbage',calories=7,serving='1 leaf (22 g)', foodType='default'),
Food(name= 'Rutabaga',calories=147,serving='1 rutabaga (386 g)', foodType='default'),
Food(name= 'Shallots',calories=18,serving='1 shallot (25 g)', foodType='default'),
Food(name= 'Spinach',calories=78,serving='1 bunch (340 g)', foodType='default'),
Food(name= 'Squash',calories=88,serving='1 squash (196 g)', foodType='default'),
Food(name= 'Sweet Potato',calories=112,serving='1 potato (130 g)', foodType='default'),
Food(name= 'Tomato',calories=20,serving='1 tomato (111 g)', foodType='default'),
Food(name= 'Turnip Greens',calories=34,serving='1 turnip green (170 g)', foodType='default'),
Food(name= 'Turnips',calories=34,serving='1 turnip (122 g)', foodType='default'),
Food(name= 'Wasabi',calories=184,serving='1 root (169 g)', foodType='default'),
Food(name= 'Winter Squash',calories=147,serving='1 squash (431 g)', foodType='default'),
Food(name= 'Zucchini',calories=33,serving='1 zucchini (196 g)', foodType='default'),
Food(name= '7up',calories=156,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'Barq’s',calories=163,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'Bitter Lemon',calories=121,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'Canada Dry Ginger Ale',calories=98,serving='8 fl. oz. (240 ml)', foodType='default'),
Food(name= 'Cherry Coke',calories=156,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'Coke',calories=149,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'Coke Zero',calories=0,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'Diet Cherry Coke',calories=4,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'Diet Coke',calories=4,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'Diet Dr. Pepper',calories=0,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'Diet Pepsi',calories=0,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'Diet Sunkist',calories=0,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'Dr. Brown’s',calories=188,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'Dr. Pepper',calories=96,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'Fanta',calories=138,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'Fanta Zero',calories=0,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'Five Alive',calories=124,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'Fresca',calories=0,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'Full Throttle',calories=264,serving='8 fl. oz. (240 ml)', foodType='default'),
Food(name= 'Fuze',calories=71,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'Fuze Tea',calories=89,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'Gatorade',calories=89,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'Ginger Ale',calories=124,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'Ice Tea',calories=96,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'Jolt Cola',calories=106,serving='8 fl. oz. (240 ml)', foodType='default'),
Food(name= 'Kool-Aid',calories=62,serving='8 fl. oz. (237 ml)', foodType='default'),
Food(name= 'Lemonade',calories=149,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'Mello Yello',calories=118,serving='8 fl. oz. (240 ml)', foodType='default'),
Food(name= 'Minute Maid',calories=110,serving='8 fl. oz. (240 ml)', foodType='default'),
Food(name= 'Minute Maid Light',calories=5,serving='8 fl. oz. (240 ml)', foodType='default'),
Food(name= 'Mug Root Beer',calories=101,serving='8 fl. oz. (240 ml)', foodType='default'),
Food(name= 'Orange Soda',calories=170,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'Pepsi',calories=156,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'Pibb Xtra',calories=142,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'Powerade',calories=600,serving='1 bottle (500 ml)', foodType='default'),
Food(name= 'Schweppes Ginger Ale',calories=135,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'Soda',calories=188,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'Sprite',calories=131,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'Sprite Zero',calories=0,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'Squirt',calories=106,serving='8 fl. oz. (240 ml)', foodType='default'),
Food(name= 'Sunkist',calories=89,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'Surge',calories=170,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'TaB',calories=0,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'Tonic Water',calories=124,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'Vanilla Coke',calories=160,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'ACE Drink',calories=220,serving='1/2 litre (500 ml)', foodType='default'),
Food(name= 'Apple Spritzer',calories=120,serving='1/2 litre (500 ml)', foodType='default'),
Food(name= 'Chai',calories=0,serving='1 cup (236 ml)', foodType='default'),
Food(name= 'Chai Tea',calories=0,serving='1 cup (236 ml)', foodType='default'),
Food(name= 'Chocolate Milk',calories=237,serving='1 cup (266 ml)', foodType='default'),
Food(name= 'Chocolate Milkshake',calories=354,serving='10 fl. oz. (283 ml)', foodType='default'),
Food(name= 'Club Mate',calories=150,serving='1/2 litre (500 ml)', foodType='default'),
Food(name= 'Coca Cola',calories=139,serving='1 can (330 ml)', foodType='default'),
Food(name= 'Coffee',calories=2,serving='1 cup (237 ml)', foodType='default'),
Food(name= 'Coke Zero',calories=3,serving='1 can (330 ml)', foodType='default'),
Food(name= 'Cola',calories=139,serving='1 can (330 ml)', foodType='default'),
Food(name= 'Crystal Light',calories=623,serving='8 fl. oz. (237 ml)', foodType='default'),
Food(name= 'Diet Coke',calories=3,serving='1 can (330 ml)', foodType='default'),
Food(name= 'Egg Cream',calories=118,serving='1 serving (125 ml)', foodType='default'),
Food(name= 'Egg Nog',calories=224,serving='1 cup (254 ml)', foodType='default'),
Food(name= 'Elderflower Cordial',calories=66,serving='8 oz. (227 ml)', foodType='default'),
Food(name= 'Evian',calories=0,serving='1 bottle (500 ml)', foodType='default'),
Food(name= 'Gatorade',calories=82,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'Ginger Tea',calories=0,serving='1 cup (254 ml)', foodType='default'),
Food(name= 'Hawaiian Punch',calories=70,serving='8 oz. (227 ml)', foodType='default'),
Food(name= 'Hi-C',calories=124,serving='12 fl. oz. (253 ml)', foodType='default'),
Food(name= 'Horchata',calories=130,serving='8 fl. oz. (240 ml)', foodType='default'),
Food(name= 'Hot Chocolate',calories=237,serving='1 cup (266 ml)', foodType='default'),
Food(name= 'Ice Tea',calories=96,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'Iced Tea',calories=96,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'Karamalz',calories=88,serving='1 cup (237 ml)', foodType='default'),
Food(name= 'Kombucha',calories=30,serving='8 oz. (227 ml)', foodType='default'),
Food(name= 'Kool-Aid',calories=62,serving='8 fl. oz. (237 ml)', foodType='default'),
Food(name= 'Lassi',calories=260,serving='1 cup (250 ml)', foodType='default'),
Food(name= 'Latte Macchiato',calories=171,serving='1 cup (300 ml)', foodType='default'),
Food(name= 'Lemonade',calories=149,serving='12 fl. oz. (355 ml)', foodType='default'),
Food(name= 'Malt Beer',calories=88,serving='1 cup (237 ml)', foodType='default'),
Food(name= 'Milk',calories=149,serving='1 cup (244 ml)', foodType='default'),
Food(name= 'Milkshake (dry)',calories=23,serving='1 tbsp (7 g)', foodType='default'),
Food(name= 'Milo',calories=98,serving='3 tbsp (24 g)', foodType='default'),
Food(name= 'Nectar',calories=120,serving='8 oz. (227 ml)', foodType='default'),
Food(name= 'Nestea',calories=86,serving='1 cup (240 ml)', foodType='default'),
Food(name= 'Non-alcoholic Beer',calories=131,serving='1 can, bottle (354 ml)', foodType='default'),
Food(name= 'Powerade',calories=80,serving='1 bottle (500 ml)', foodType='default'),
Food(name= 'Slurpee',calories=10,serving='8 oz. (240 ml)', foodType='default'),
Food(name= 'Slush Puppie',calories=119,serving='8 fl. oz. (237 ml)', foodType='default'),
Food(name= 'Smoothie',calories=89,serving='8 oz. (240 ml)', foodType='default'),
Food(name= 'Soy Milk',calories=109,serving='1 cup (243 ml)', foodType='default'),
Food(name= 'Strawberry Milkshake',calories=320,serving='10 fl. oz. (283 ml)', foodType='default'),
Food(name= 'Tang',calories=91,serving='1/8 cup (24 g)', foodType='default'),
Food(name= 'Tap Water',calories=0,serving='1 fl. oz. (29.6 ml)', foodType='default'),
Food(name= 'Tea',calories=2,serving='1 cup (237 ml)', foodType='default'),
Food(name= 'Vanilla Milkshake',calories=422,serving='10 fl. oz. (283 ml)', foodType='default'),
Food(name= 'Volvic',calories=0,serving='1/2 litre (500 ml)', foodType='default'),
Food(name= 'Water',calories=0,serving='1 fl. oz. (29.6 ml)', foodType='default'),
Food(name= 'Yerba Mate',calories=31,serving='1 serving (50 ml)', foodType='default'),
Food(name= 'Acai',calories=20,serving='1 oz. (28.35 g)', foodType='default'),
Food(name= 'Apple',calories=95,serving='1 apple (182 g)', foodType='default'),
Food(name= 'Applesauce',calories=167,serving='1 cup (246 g)', foodType='default'),
Food(name= 'Apricot',calories=17,serving='1 apricot (35 g)', foodType='default'),
Food(name= 'Avocado',calories=320,serving='1 avocado (200 g)', foodType='default'),
Food(name= 'Banana',calories=111,serving='1 banana (125 g)', foodType='default'),
Food(name= 'Blackberries',calories=62,serving='1 cup (144 g)', foodType='default'),
Food(name= 'Blood Oranges',calories=70,serving='1 serving (140 g)', foodType='default'),
Food(name= 'Blueberries',calories=84,serving='1 cup (148 g)', foodType='default'),
Food(name= 'Cantaloupe',calories=23,serving='1 wedge (69 g)', foodType='default'),
Food(name= 'Cherries',calories=4,serving='1 cherry (8 g)', foodType='default'),
Food(name= 'Clementine',calories=35,serving='1 clementine (74 g)', foodType='default'),
Food(name= 'Cranberries',calories=46,serving='1 cup (100 g)', foodType='default'),
Food(name= 'Currants',calories=63,serving='1 cup (112 g)', foodType='default'),
Food(name= 'Custard Apple',calories=136,serving='1 custard apple (135 g)', foodType='default'),
Food(name= 'Dates',calories=20,serving='1 date (7.1 g)', foodType='default'),
Food(name= 'Figs',calories=37,serving='1 fig (50 g)', foodType='default'),
Food(name= 'Fruit salad',calories=125,serving='1 cup (249 g)', foodType='default'),
Food(name= 'Grapes',calories=104,serving='1 cup (151 g)', foodType='default'),
Food(name= 'Greengage',calories=2,serving='1 fruit (5 g)', foodType='default'),
Food(name= 'Guava',calories=37,serving='1 guava (55 g)', foodType='default'),
Food(name= 'Jackfruit',calories=143,serving='1 cup (151 g)', foodType='default'),
Food(name= 'Jujube',calories=22,serving='1 oz. (28.35 g)', foodType='default'),
Food(name= 'Kiwi',calories=112,serving='1 Kiwi (183 g)', foodType='default'),
Food(name= 'Lemon',calories=17,serving='1 lemon (58 g)', foodType='default'),
Food(name= 'Lime',calories=20,serving='1 lime (67 g)', foodType='default'),
Food(name= 'Lychees',calories=7,serving='1 lychee (10 g)', foodType='default'),
Food(name= 'Mandarin Oranges',calories=47,serving='1 mandarin orange (88 g)', foodType='default'),
Food(name= 'Mango',calories=202,serving='1 mango (336 g)', foodType='default'),
Food(name= 'Minneola',calories=70,serving='1 minneola (109 g)', foodType='default'),
Food(name= 'Mulberries',calories=60,serving='1 cup (140 g)', foodType='default'),
Food(name= 'Nectarine',calories=66,serving='1 nectarine (150 g)', foodType='default'),
Food(name= 'Olives',calories=2,serving='1 olive (2.7 g)', foodType='default'),
Food(name= 'Orange',calories=62,serving='1 orange (131 g)', foodType='default'),
Food(name= 'Papaya',calories=215,serving='1 fruit (500 g)', foodType='default'),
Food(name= 'Passion Fruit',calories=17,serving='1 passoin fruit (18 g)', foodType='default'),
Food(name= 'Peach',calories=59,serving='1 peach (150 g)', foodType='default'),
Food(name= 'Pear',calories=101,serving='1 pear (178 g)', foodType='default'),
Food(name= 'Persimmon',calories=32,serving='1 fruit (25 g)', foodType='default'),
Food(name= 'Physalis',calories=2,serving='1 berry (5 g)', foodType='default'),
Food(name= 'Pineapple',calories=453,serving='1 pineapple (905 g)', foodType='default'),
Food(name= 'Plantains',calories=218,serving='1 plantain (179 g)', foodType='default'),
Food(name= 'Plum',calories=30,serving='1 plum (66 g)', foodType='default'),
Food(name= 'Pomegranate',calories=234,serving='1 pomegranate (282 g)', foodType='default'),
Food(name= 'Quince',calories=52,serving='1 quince (92 g)', foodType='default'),
Food(name= 'Raisins',calories=434,serving='1 cup (145 g)', foodType='default'),
Food(name= 'Rambutan',calories=7,serving='1 rambutan (9 g)', foodType='default'),
Food(name= 'Raspberries',calories=64,serving='1 cup (123 g)', foodType='default'),
Food(name= 'Rhubarb',calories=11,serving='1 stalk (51 g)', foodType='default'),
Food(name= 'Starfruit',calories=28,serving='1 star fruit (91 g)', foodType='default'),
Food(name= 'Strawberries',calories=49,serving='1 cup (152 g)', foodType='default'),
Food(name= 'Tamarind',calories=5,serving='1 tamarind (2 g)', foodType='default'),
Food(name= 'Tangerine',calories=47,serving='1 tangerine (88 g)', foodType='default'),
Food(name= 'Watermelon',calories=86,serving='1 wedge (286 g)', foodType='default')
]