"""changes

Revision ID: bd95c4d308af
Revises: a5cfb12ed9cd
Create Date: 2021-06-09 11:51:39.181416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd95c4d308af'
down_revision = 'a5cfb12ed9cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exerciseEntries', 'exercise_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exerciseEntries', 'exercise_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
