"""test

Revision ID: 7d7c535e488f
Revises: f58b1f252c42
Create Date: 2021-06-11 00:08:09.770640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d7c535e488f'
down_revision = 'f58b1f252c42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
