"""changed exercise entry model'



Revision ID: a5cfb12ed9cd
Revises: ab62ad2a05ad
Create Date: 2021-06-09 10:42:25.633004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5cfb12ed9cd'
down_revision = 'ab62ad2a05ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exerciseEntries', 'exerciseType')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exerciseEntries', sa.Column('exerciseType', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
