"""changes

Revision ID: 64912e231e3e
Revises: bd95c4d308af
Create Date: 2021-06-09 13:10:06.251309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64912e231e3e'
down_revision = 'bd95c4d308af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'weight',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'weight',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
