"""changed user model

Revision ID: f58b1f252c42
Revises: 64912e231e3e
Create Date: 2021-06-10 17:31:47.860259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f58b1f252c42'
down_revision = '64912e231e3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exerciseEntries', 'exercise_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'weight',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'weight',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('exerciseEntries', 'exercise_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
